## What is Logistic Regression?
Logistic regression is a supervised learning algorithm used for binary classification problems. It predicts the probability of an outcome that can be binary (0 or 1, yes or no, true or false). The algorithm uses a __sigmoid function__ to predict probabilities that map between 0 and 1.

__Steps:__
1) Load the dataset.
2) Perform data preprocessing (if needed).
3) Split the dataset into training and testing sets.
4) Train the logistic regression model.
5) Evaluate the model using accuracy score, confusion matrix, and other metrics.

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [ ]:
df = pd.read_csv(r'C:\\Users\\Asus\\Desktop\\Logistic Regression-20241008T111851Z-001\\Logistic Regression\\heart.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Asus\\\\Desktop\\\\Logistic Regression-20241008T111851Z-001\\\\Logistic Regression\\\\heart.csv'

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
Dataset Description
The dataset used for this project is the Heart Disease dataset from the UCI Machine Learning Repository. It contains data collected from various patients, including demographic, lifestyle, and clinical variables. Specifically, the dataset includes 303 instances and 14 attributes, which are:

age: Age of the patient in years
sex: Sex of the patient (1 = male, 0 = female)
cp: Chest pain type (0 = typical angina, 1 = atypical angina, 2 = non-anginal pain, 3 = asymptomatic)
trestbps: Resting blood pressure in mm Hg on admission to the hospital
chol: Serum cholesterol in mg/dl
fbs: Fasting blood sugar > 120 mg/dl (1 = true, 0 = false)
restecg: Resting electrocardiographic results (0 = normal, 1 = having ST-T wave abnormality, 2 = showing probable or definite left ventricular hypertrophy by Estes' criteria)
thalach: Maximum heart rate achieved
exang: Exercise-induced angina (1 = yes, 0 = no)
oldpeak: ST depression induced by exercise relative to rest
slope: The slope of the peak exercise ST segment (0 = upsloping, 1 = flat, 2 = downsloping)
ca: Number of major vessels (0-3) colored by fluoroscopy
thal: Thalassemia (3 = normal, 6 = fixed defect, 7 = reversible defect)
target: Diagnosis of heart disease (1 = presence of heart disease, 0 = absence of heart disease)

SyntaxError: unterminated string literal (detected at line 10) (<ipython-input-2-7b3087589afe>, line 10)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [ ]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\dell\Desktop\Training\Batch 1\Data Analysis\batch1\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [ ]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8439024390243902
Accuracy of Decision Trees 0.9804878048780488


In [ ]:
confusion_matrix(y_test,y_pred1)

array([[83, 22],
       [10, 90]])

In [ ]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  83  22
1  10  90

In [ ]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0    1
0  101    4
1    0  100

In [ ]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [ ]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
685             0                               0                         0
933             0                               1                         0
236             0                               0                         0
710             1                               1                         1
641             0                               0                         0
418             1                               1                         1
814             1                               1                         1
817             1                               1                         1
343             1                               1                         1
311             0                               0                         0

In [ ]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [ ]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  83  22
1  10  90
--------------------------------------------------
Precision -  0.8035714285714286
Recall -  0.9
F1 score -  0.8490566037735849


In [ ]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
     0    1
0  101    4
1    0  100
--------------------------------------------------
Precision -  0.9615384615384616
Recall -  1.0
F1 score -  0.9803921568627451


In [ ]:
precision_score(y_test,y_pred1,average=None)

array([0.89247312, 0.80357143])

In [ ]:
precision_score(y_test,y_pred2,average=None)

array([1.        , 0.96153846])

In [ ]:
recall_score(y_test,y_pred2,average=None)

array([0.96190476, 1.        ])